### ISSUE TITLE
App crashes while voting on an Evmos proposal

### ISSUE THREAD

**Issue by mdmohsin7** [cosmostation/cosmostation-android#124]
The crash happened only once. In next two subsequent voting, there was no issue.
This was the stack trace and message when the app crashed.

```
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void wannabit.io.cosmostaion.base.BaseFragment.onRefreshTab()' on a null object reference
--
  | stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void wannabit.io.cosmostaion.base.BaseFragment.onRefreshTab()' on a null object reference
  | at wannabit.io.cosmostaion.activities.VoteActivity$1.onPageSelected(VoteActivity.java:94)
  | at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
  | at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:665)
  | at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
  | at androidx.viewpager.widget.ViewPager.onRestoreInstanceState(ViewPager.java:1462)
  | at android.view.View.dispatchRestoreInstanceState(View.java:21018)
  | at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4000)
  | at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
  | at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
  | at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
  | at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4006)
  | at android.view.View.restoreHierarchyState(View.java:20996)
  | at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2225)
  | at android.app.Activity.onRestoreInstanceState(Activity.java:1723)
  | at android.app.Activity.performRestoreInstanceState(Activity.java:1676)
  | at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1379)
  | at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3676)
  | at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
  | at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
  | at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
  | at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  | at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
  | at android.os.Handler.dispatchMessage(Handler.java:106)
  | at android.os.Looper.loopOnce(Looper.java:201)
  | at android.os.Looper.loop(Looper.java:288)
  | at android.app.ActivityThread.main(ActivityThread.java:7835)
  | at java.lang.reflect.Method.invoke(Native Method)
  | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
  | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Kwonhyukjoon** [comment]
Thank you!
I'll find the cause and fix .
