### ISSUE TITLE
App crashes after selecting any option in delegate tab

### ISSUE THREAD

**Issue by mdmohsin7** [cosmostation/cosmostation-android#63]
This issue happens whenever I try to go into the delegate tab and select any option right after refreshing the data.
This was the log when app crashed.

```
time: 1642750390222
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{wannabit.io.cosmostaion/wannabit.io.cosmostaion.activities.ReInvestActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7835)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at wannabit.io.cosmostaion.activities.ReInvestActivity.onCreate(ReInvestActivity.java:59)
	at android.app.Activity.performCreate(Activity.java:8050)
	at android.app.Activity.performCreate(Activity.java:8030)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1332)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
	... 12 more
```

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-android/releases/tag/v1.5.38

**Comment by wannabit-yongjoo** [comment]
Thanks a lot for report!
